### PR TITLE
Implemented #122 Empty and Null validators

### PR DESCRIPTION
**Pull request by regisbsb**
Please double check if it's only that is necessary or do I need to modify more files to properly add them.

Cheers
#122

### CODE REVIEW

**Comment by JeremySkinner** [comment]
Thanks for this...could you add some corresponding unit tests too? Thanks

**Comment by regisbsb** [comment]
@JeremySkinner unit tests added!

**Comment by JeremySkinner** [comment]
Looks good...I'll merge this in, but I noticed the default messages were changed for NotNull. I'm not really keen on this - can we put them back to how it was? If we want to change it, we'd also need to change all the other translations, but I actually prefer it to say "empty" rather than "null"

**Comment by regisbsb** [comment]
Agreed. I'll follow the same logic then.

**Comment by regisbsb** [comment]
Done.

**Comment by JeremySkinner** [comment]
Thanks, I've merged it in

**Pull request merged**
