### PR TITLE
Enum validator

### PR DESCRIPTION
**Pull request by Lechus**
Validate if enum value is defined in Enum.
Credits to @Bobby B from stackoverflow.com

### CODE REVIEW

**Comment by Lechus** [comment]
@JeremySkinner It does not work with Nullable Enum.
Quick fix could be something like:

	
	protected override bool IsValid(PropertyValidatorContext context) {
			
            //Nullable Enum
            Type enumType = Nullable.GetUnderlyingType(_enumType) ?? _enumType;
            
            if (!enumType.IsEnum() || null == context.PropertyValue) return false;

            return Enum.IsDefined(enumType, context.PropertyValue);
		}

**Comment by JeremySkinner** [comment]
Good catch....I'll make the change to check the underlying type.

However, I'm not really happy with the validator failing if the property value is null....this isn't really consistent with the rest of FluentValidation- the other validators typically treat null as valid, and you have to explicitly chain the NotNull() validator if you want nulls to fail validation. 

Is that OK?

**Comment by Lechus** [comment]
I added to `
Person {
  public EnumGender? NullableGender { get; set; }
}
`

Tests updated with:
```
           nullableValidator = new TestValidator {
                v => v.RuleFor(x => x.NullableGender).NotNull().IsInEnum()
            };
```

Test:

       [Fact]
        public void When_the_Nullableenum_is_not_initialized_with_valid_value_then_the_validator_should_fail()
        {
            var result = nullableValidator.Validate(new Person());
            result.IsValid.ShouldBeFalse();
        }

Test fails because Enum.IsDefined() throws Exception: System.ArgumentNullException.
That's why there is the validator failing if the property value is null.

**Comment by Lechus** [comment]
Test will pass if I StopOnFirstFailure:
```
            nullableValidator = new TestValidator {
                v => v.RuleFor(x => x.NullableGender).Cascade(CascadeMode.StopOnFirstFailure).NotNull().IsInEnum()
            };
```

but I bet You know better solution.

**Comment by JeremySkinner** [comment]
No need really for a test in that particular case, as it's actually testing the NotNull rather than the enumvalidator. 

Here are the tests I've added:

```
[Fact]
public void Nullable_enum_valid_when_property_value_is_null()
{
    var validator = new InlineValidator<Foo>();
        validator.RuleFor(x => x.Gender).IsInEnum();
    var result = validator.Validate(new Foo());
    result.IsValid.ShouldBeTrue();
}

[Fact]
public void Nullable_enum_valid_when_value_specified()
{
    var validator = new InlineValidator<Foo>();
    validator.RuleFor(x => x.Gender).IsInEnum();
    var result = validator.Validate(new Foo() { Gender = EnumGender.Male });
    result.IsValid.ShouldBeTrue();
}

[Fact]
public void Nullable_enum_invalid_when_bad_value_specified()
{
    var validator = new InlineValidator<Foo>();
    validator.RuleFor(x => x.Gender).IsInEnum();
    var result = validator.Validate(new Foo() { Gender = (EnumGender)42 });
    result.IsValid.ShouldBeFalse();
}

public class Foo
{
    public EnumGender? Gender { get; set; }
}
```

**Comment by JeremySkinner** [comment]
I also just noticed that the error message for EnumValidator isn't localised like the others. I'll get that fixed too.

**Comment by Lechus** [comment]
I see now. Cool. Let it be consistent!
Cheers!

**Comment by JeremySkinner** [comment]
I've pushed this out as v6.2.1

**Comment by Lechus** [comment]
Thank you.

**Pull request merged**
