### PR TITLE
Typo fixed in Slovak translation

### PR DESCRIPTION
**Pull request by andrjfrks**

### CODE REVIEW

**Comment by JeremySkinner** [comment]
Merged, thanks

**Comment by andrjfrks** [comment]
When it's gonna be available on Nuget pls?

**Comment by JeremySkinner** [comment]
It'll be part of 8.5-preview5, probably in the next couple of weeks when I get some time.

**Comment by JeremySkinner** [comment]
8.5.0-preview5 is released with this change.

**Pull request merged**
