### PR TITLE
Fluent tests

### PR DESCRIPTION
**Pull request by smurtdev**
Implemented #82 More fluent validation tests :

```csharp

var validator = new ItemValidator();

 var testValidationResult = validator.TestValidate(new Item 
{ 
  IntProperty = 4, 
  StringProperty = "ww", 
  SubItem = new SubItem 
  { 
     IntProperty1 = 2, 
     StringProperty1 = "55" 
  } 
});

 testValidationResult.Which
                     .Property(x => x.SubItem)
                     .Property(x => x.IntProperty1)
                     .ShouldHaveError()
                     .When(x => x.ErrorCode == "inclusivebetween_error");

// or

 testValidationResult.Which
                     .Property(x => x.SubItem)
                     .Property(x => x.IntProperty1)
                     .ShouldHaveError()
                     .WithErrorCode("inclusivebetween_error");

```

### CODE REVIEW

**Comment by JeremySkinner** [comment]
Please could you rebase this onto master, and collapse the commits into just 1? This'll make it much easier to review (sorry for taking so long to reply  - I've had a very busy few months).

Thanks

**Comment by smurtdev** [comment]
OK. Probably I'll be able to do it on holidays.

Regards,
Yevgen Cherkes

**Comment by smurtdev** [comment]
Combined in one commit:

https://github.com/smurtdev/FluentValidation/commit/8455d52ce2bce058991e208289d74a62ab13315d

**Comment by JeremySkinner** [comment]
Not quite sure what happened, as there still seemed to be multiple commits. Also, the build was broken as somehow duplicate resource files had been inserted into the main csproj.

Anyway, I've now fixed this, collapsed this into one commit and merged into master. 

In future, it would be really helpful if you could use tabs rather than spaces for indentation for consistency with the rest of the project.

Thanks for the contribution! It's very much appreciated. Sorry it took so long to get it merged in.

**Pull request closed without merging**
