### PR TITLE
Timeout for custom validator.

### PR DESCRIPTION
**Pull request by andrechi1**
Timeout for custom validator. 

I've put 100 milliseconds fixed. It might be better to put something configurable.

### CODE REVIEW

**Comment by JeremySkinner** [comment]
Could you provide some details on the use case for this? The AsyncPredicateValidator is designed to be executed asynchronously - you should never be running it synchronously at all.

**Comment by andrechi1** [comment]
My problem is that I want to do a validation on the server. And sometimes it takes too long and the phone is stopped.

CancellationToken is used next to CancellationTokenSource, in order to stop the asynchronous function. In this case it stops if it takes 100 milliseconds to validate.

**Comment by JeremySkinner** [comment]
I’m not following. The change you made to AsyncPredicateValidator is to a *synchronous* method which you shouldn’t be calling.

**Comment by JeremySkinner** [comment]
Just to clarify that further - you should be passing your CancellationToken (with timeout preconfigured) to the root caldiator’s ValidateAsync method. It will be propagated to all the child validators.

**Comment by andrechi1** [comment]
I've changed all the CancellationToken by New CancellationTokenSource (100). Token. I don't know if somewhere is not to be done.

In My code is something similar to

RuleFor(x => x.Password).CustomAsync(async (password, ctx, cancel) =>
{
      var errors = ValidatePassword(password, cancel);

      foreach (var error in erros)
      {
            ctx.AddFailure(error.Description);
      }
}

**Comment by JeremySkinner** [comment]
As I said previously, you need to specify your CancellationToken as *part of the call to ValidateAsync on your root level validator*.

**Comment by andrechi1** [comment]
I've seen how do it. Thank you.

**Pull request closed without merging**
