### PR TITLE
Added Brazilian-PT translation and fixed translation typos for PT-BR.

### PR DESCRIPTION
**Pull request by morilon**
Current portuguese translation doesn't add up to the way we actually speak. I can answer any questions you guys might have.

### CODE REVIEW

**Comment by JeremySkinner** [comment]
Thanks, I’ve merged this in, although was this supposed to contain fixed for the current Portuguese translations too?

**Comment by morilon** [comment]
No, Just the portuguese version, since I'm not native from Portugal, I wasn't sure whether the translations are correct or not, so I thought it was best just to add the Brazilian version instead. :)

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by JeremySkinner** [comment]
That’s great, thanks!

**Comment by morilon** [comment]
No problem, thank you!

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Pull request merged**
