### PR TITLE
Add Welsh language file

### PR DESCRIPTION
**Pull request by LaurieGPicken**

### CODE REVIEW

**Comment by JeremySkinner** [comment]
Thanks for this. Please could you make the following changes:
- Please could you make sure all braces are on the end of the line for consistency with the rest of the project 
- It'll need adding to the `LanguageManager`, or FluentValidation won't actually pick it up (this is why the CI pipeline failed): https://github.com/JeremySkinner/FluentValidation/blob/master/src/FluentValidation/Resources/LanguageManager.cs#L35

Thanks again!

**Comment by LaurieGPicken** [comment]
Apologies for the positioning of the braces, that was Prettier interfering, should be consistent now.
Have I sufficiently added Welsh to LanguageManager there? I can see see the builds are still failing.

**Comment by JeremySkinner** [comment]
Merged, thanks

**Comment by LaurieGPicken** [comment]
Brilliant, thanks for merging it.
Is there any chance you have a rough idea of when the next release/preview release will be?
Obviously I can implement `ILanguageManager` to use these new translations but it would be great if they were handled by default.
We appreciate all the work you put in to this, thanks again.

**Comment by JeremySkinner** [comment]
I wasn't planning another release before 8.5, which won't be until asp.net core 3 is released (which is due september)

**Comment by JeremySkinner** [comment]
I can aim to push out an 8.5-preview3 with this in though if you don't mind working with a preview release.

**Comment by LaurieGPicken** [comment]
> I can aim to push out an 8.5-preview3 with this in though if you don't mind working with a preview release.

That would be superb, we're comfortable using a preview release.

**Comment by JeremySkinner** [comment]
That's done. Might take a little while for nuget to index it and it shows up in the package feed

**Comment by LaurieGPicken** [comment]
Installed the updated package and it's now working out-of-the-box for Welsh translations, thanks ever so much.

**Pull request merged**
