### PR TITLE
GitHub project URL

### LINKED ISSUE #128: Find and replace http://www.codeplex.com/FluentValidation
All the source code have this url in the header. Could we find and replace to the github one?

### PR DESCRIPTION
**Pull request by DixonDs**
Fixes #128

### CODE REVIEW

**Comment by DixonDs** [comment]
Hi @JeremySkinner ! Shall I close this PR?

**Comment by JeremySkinner** [comment]
Thanks, yes I made this change a while back.

**Comment by DixonDs** [comment]
@JeremySkinner The rebased PR still had 16 files where those urls were pointing to CodePlex

**Comment by JeremySkinner** [comment]
Thanks - that's fixed.

**Pull request closed without merging**
