### PR TITLE
Added lambdas on LengthValidator and RegularExpressionValidator to ac…

### LINKED ISSUE #92: Access to validator instance properties when using property validators in a rule
Hello,

When I define an AbstractValidator for a class, I want to be able to access my class properties as parameters for the property validators the same way I can pick the property to validate when calling RuleFor()

Example:
```c#
public class TextFieldValidator : AbstractValidator<TextField>
    {
        public TextFieldValidator()
        {
            When(t => !string.IsNullOrEmpty(t.Regex), () =>
            {
                // This doesn't work
                RuleFor(t => t.Value).Matches(t => t.Regex); 
            });
        }
    }
```

There is a workaround to do something like that?
Is it planned to add that feature in a future version?

### PR DESCRIPTION
**Pull request by emisand**
Added lambdas on LengthValidator and RegularExpressionValidator to access properties from the validator instance. This closes #92

### CODE REVIEW

**Comment by JeremySkinner** [comment]
Thanks for this. A few comments:

- You should use Func<T, int> rather than Expression<Func<T, int>> etc so you don't need to compile the expression. You'd only need to use an expression if you need to get metadata about the lambda, but in this case it isn't neccessary - we just need the delegate itself

- I don't think the casts to int in LengthValidator line 58 are neccessary

- Please could you use tabs rather than spaces for indentation for consistency with the rest of the project

- The changes to Regex validator on line 39 mean that you can no longer pass in a pre-configured RegEx instance. This behaviour needs to be maintained - I'd suggest storing it inside the lambda: `this.regexFunc = x => regex;`  

- Please could you add appropriate unit tests for the new methods 

If you can make these changes then I'll merge this in.

Thanks!

**Comment by emisand** [comment]
I have made all the changes you noted.

Please note that when Lambdas are used for the modified validators, properties like Min or Max in the LengthValidator or Expression in RegularExpressionValidator may not be accesible before IsValid is called, because lambdas are excecuted inside IsValid. Let me know if this is an acceptable behavior.

Thank you.

**Comment by JeremySkinner** [comment]
Thanks - this looks good. I'll try and merge it later today. 

I think the behaviour for Min/Max etc is fine, but it may be worth introducing an extra property on the validators so you can check whether or not they're accessible for metadata purposes (IsMetadataReady or something like that). I'll have a think about this.

**Comment by JeremySkinner** [comment]
I've merged this into the latest commit. Thanks again.

**Comment by emisand** [comment]
I've found a problem with this that we shold think how to fix.

When using this new lambdas for fluent validation with the MVC5 project, the client validation rules are not generated correctly because the code that generates this client validation rules does not use the ValidationContext to evaluate the lambdas.

What do you recommend me to evaluate the lambdas and fill the validation properties before the client validation rules are generated?
If you have any ideas, I will try to fix it and submit a pull request.

Thank you.

**Comment by JeremySkinner** [comment]
There isn't any contextual information when generating client-side rules, so anything that is cross-property won't work client-side. I'd suggest modifying the clientside adaptors to explicitly skip trying to generate client-side rules when using the lambda-based overloads, and assume they are server-side only.

**Pull request closed without merging**
