### PR TITLE
Various performance improvements during validation

### PR DESCRIPTION
**Pull request by batzen**
This PR primarily focuses on caching and skipping/delaying things done during validation.
Especially the creation of validation errors.

In my tests (some posted in #331) these changes brought about 6 times better performance and cut memory traffic in half.
Used a validator with just two rules in my tests.

### CODE REVIEW

**Comment by batzen** [comment]
@JeremySkinner Any chance you could spare some time to have a look at this PR?

**Comment by JeremySkinner** [comment]
I will try and do so soon...I don't get much time to work on FluentValidation and when I do, I've had to focus on aspnetcore compatibility.

**Comment by batzen** [comment]
Didn't want to pressure you. Just wanted to make sure you don't forget about it. ;-)

**Comment by JeremySkinner** [comment]
Thanks for doing this. I've had quick initial first look this morning. Some comments:

- In MessageFormatter.cs, the switch statement in GetPlaceholder could use the PropertyName/PropertyValue constants rather than duplicating the names.
https://github.com/JeremySkinner/FluentValidation/pull/334/commits/746fc512c78196054a9ebde2628f1a7688ebfb6f

- In PropertyValidatorContext.cs, is there a benefit of making the MessageFormatter lazily instantiated? The MessageFormatter is used by pretty much all of the validators, so would this one make more sense to stay as it was before?
https://github.com/JeremySkinner/FluentValidation/pull/334/commits/e52d12663cd2f5fd772e53df551c404ea264fdc3

- In PropertyRule.cs, the caching of the DisplayName is going to cause problems as this means you can no longer lazily load the property name from a custom IStringSource. I've seen people use custom implementations that aren't necessarily tied to culture, so this change will need removing. 

- In PropertyValidator.cs, moving the AppendPropertyName and AppendArgument("PropertyValue") calls into CreateValidationError is a subtle but large breaking change, as anyone overriding CreateValidationError will no longer have these values automatically available, so this will need to go back to how it was before.

**Comment by batzen** [comment]
- Will use those constants.

- Instantiating it lazily has much benefit. MessageFormatter is only needed if you create a ValidationFailure and/or want to format a message. Thus it's not needed for validations that succeed.

- People can still use their own IStringSource. But their result would be cached. The only problem that could pop up is if their IStringSource returns different results when called at a different point in time. My guess is that there are people using IStringSource but not returning different results at different points in time. I could add an option to ValidatorOptions called "CacheDisplayNameInPropertyRule" if you'd prefer that. Caching DisplayName contributes much to these performance improvements. Maybe you got a better idea on how to detect if the cache is valid or not.

- But you agree that AppendPropertyName etc. should only be called if validation does not succeed, don't you? If you agree i would add the calls back to the validate methods, introduce a new virtual method called "PrepareMessageFormatterForValidationError" and call that method conditionally.

**Comment by JeremySkinner** [comment]
> Instantiating it lazily has much benefit. MessageFormatter is only needed if you create a ValidationFailure and/or want to format a message. Thus it's not needed for validations that succeed.

Ok great, I'm happy with that. 

> My guess is that there are people using IStringSource but not returning different results at different points in time

There are also people who are returning different results at different points in time....that's the whole point of having IStringSource. I don't want this one cached, and I'd rather not have an extra configuration entry for it, so we'll leave it as per the original implementation.

> But you agree that AppendPropertyName etc. should only be called if validation does not succeed, don't you? 

Yes, that's sounds good.

**Comment by JeremySkinner** [comment]
How about I add an interceptor that allows you to wrap IStringSource implementations with your own version that provide caching? This way you can add the caching into your project without it affecting the core implementation?

**Comment by batzen** [comment]
I get your point and will revert my DisplayName caching changes.

There is no need to add a way of interception as that already exists. ;-)
Replacing DisplayNameResolver with a CachedDisplayNameResolver or something like that already works.
Writing that one was my first try while improving performance in that area but it didn't work very well.
Maybe i'll give it another try as soon as i got some time.

**Comment by batzen** [comment]
Made the changes you requested.

Could you @JeremySkinner give it another look?

**Comment by JeremySkinner** [comment]
Looks good, thanks. Could you squash these into a single commit? I'll then get this merged in.

**Comment by batzen** [comment]
Damn, something went wrong while squashing...

**Comment by batzen** [comment]
Should be ok now.

**Comment by JeremySkinner** [comment]
Merged, thanks!

**Pull request merged**
